# Generated by Django 4.2.4 on 2023-08-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_image_news_image1_news_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
